#!/bin/bash
pip install	absl-py
pip install	alabaster
pip install	albumentations
pip install	altair
pip install	astor
pip install	astropy
pip install	atari-py
pip install	atomicwrites
pip install	attrs
pip install	audioread
pip install	autograd
pip install	Babel
pip install	backcall
pip install	backports.tempfile
pip install	backports.weakref
pip install	beautifulsoup4
pip install	bleach
pip install	blis
pip install	bokeh
pip install	boto
pip install	boto3
pip install	botocore
pip install	Bottleneck
pip install	branca
pip install	bs4
pip install	bz2file
pip install	cachetools
pip install	certifi
pip install	cffi
pip install	chainer
pip install	chardet
pip install	cityhash
pip install	Click
pip install	cloudpickle
pip install	cmake
pip install	colorlover
pip install	community
pip install	contextlib2
pip install	convertdate
pip install	coverage
pip install	coveralls
pip install	crcmod
pip install	cufflinks
pip install	cvxopt
pip install	cvxpy
pip install	cycler
pip install	cymem
pip install	Cython
pip install	daft
pip install	dask
pip install	dataclasses
pip install	datascience
pip install	decorator
pip install	defusedxml
pip install	dill
pip install	distributed
pip install	Django
pip install	dlib
pip install	dm-sonnet
pip install	docopt
pip install	docutils
pip install	dopamine-rl
pip install	easydict
pip install	ecos
pip install	editdistance
pip install	en-core-web-sm
pip install	entrypoints
pip install	enum34
pip install	ephem
pip install	et-xmlfile
pip install	fa2
pip install	fancyimpute
pip install	fastai
pip install	fastcache
pip install	fastdtw
pip install	fastprogress
pip install	fastrlock
pip install	fbprophet
pip install	feather-format
pip install	featuretools
pip install	filelock
pip install	fix-yahoo-finance
pip install	Flask
pip install	folium
pip install	future
pip install	gast
pip install	GDAL
pip install	gdown
pip install	gensim
pip install	geographiclib
pip install	geopy
pip install	gevent
pip install	gin-config
pip install	glob2
pip install	google
pip install	google-api-core
pip install	google-api-python-client
pip install	google-auth
pip install	google-auth-httplib2
pip install	google-auth-oauthlib
pip install	google-cloud-bigquery
pip install	google-cloud-core
pip install	google-cloud-datastore
pip install	google-cloud-language
pip install	google-cloud-storage
pip install	google-cloud-translate
pip install	google-colab
pip install	google-pasta
pip install	google-resumable-media
pip install	googleapis-common-protos
pip install	googledrivedownloader
pip install	graph-nets
pip install	graphviz
pip install	greenlet
pip install	grpcio
pip install	gspread
pip install	gspread-dataframe
pip install	gunicorn
pip install	gym
pip install	h5py
pip install	HeapDict
pip install	holidays
pip install	html5lib
pip install	httpimport
pip install	httplib2
pip install	humanize
pip install	hyperopt
pip install	ideep4py
pip install	idna
pip install	image
pip install	imageio
pip install	imagesize
pip install	imbalanced-learn
pip install	imblearn
pip install	imgaug
pip install	importlib-metadata
pip install	imutils
pip install	inflect
pip install	intel-openmp
pip install	intervaltree
pip install	ipykernel
pip install	ipython
pip install	ipython-genutils
pip install	ipython-sql
pip install	ipywidgets
pip install	itsdangerous
pip install	jdcal
pip install	jedi
pip install	jieba
pip install	Jinja2
pip install	jmespath
pip install	joblib
pip install	jpeg4py
pip install	jsonschema
pip install	jupyter
pip install	jupyter-client
pip install	jupyter-console
pip install	jupyter-core
pip install	kaggle
pip install	kapre
pip install	Keras
pip install	Keras-Applications
pip install	Keras-Preprocessing
pip install	keras-vis
pip install	kiwisolver
pip install	knnimpute
pip install	librosa
pip install	lightgbm
pip install	llvmlite
pip install	lmdb
pip install	lucid
pip install	lunardate
pip install	lxml
pip install	magenta
pip install	Markdown
pip install	MarkupSafe
pip install	matplotlib
pip install	matplotlib-venn
pip install	mesh-tensorflow
pip install	mido
pip install	mir-eval
pip install	missingno
pip install	mistune
pip install	mkl
pip install	mlxtend
pip install	more-itertools
pip install	moviepy
pip install	mpi4py
pip install	mpmath
pip install	msgpack
pip install	multiprocess
pip install	multitasking
pip install	murmurhash
pip install	music21
pip install	natsort
pip install	nbconvert
pip install	nbformat
pip install	networkx
pip install	nibabel
pip install	nltk
pip install	nose
pip install	notebook
pip install	np-utils
pip install	numba
pip install	numexpr
pip install	numpy
pip install	nvidia-ml-py3
pip install	oauth2client
pip install	oauthlib
pip install	okgrade
pip install	olefile
pip install	opencv-contrib-python
pip install	opencv-python
pip install	openpyxl
pip install	osqp
pip install	packaging
pip install	pandas
pip install	pandas-datareader
pip install	pandas-gbq
pip install	pandas-profiling
pip install	pandocfilters
pip install	parso
pip install	pathlib
pip install	patsy
pip install	pexpect
pip install	pickleshare
pip install	Pillow
pip install	pip
pip install	pip-tools
pip install	plac
pip install	plotly
pip install	pluggy
pip install	portpicker
pip install	prefetch-generator
pip install	preshed
pip install	pretty-midi
pip install	prettytable
pip install	progressbar2
pip install	prometheus-client
pip install	promise
pip install	prompt-toolkit
pip install	protobuf
pip install	psutil
pip install	psycopg2
pip install	ptyprocess
pip install	py
pip install	pyarrow
pip install	pyasn1
pip install	pyasn1-modules
pip install	pycocotools
pip install	pycparser
pip install	pydot
pip install	pydot-ng
pip install	pydotplus
pip install	pyemd
pip install	pyglet
pip install	Pygments
pip install	pygobject
pip install	pymc3
pip install	pymongo
pip install	pymystem3
pip install	PyOpenGL
pip install	pyparsing
pip install	pyrsistent
pip install	pysndfile
pip install	PySocks
pip install	pystan
pip install	pytest
pip install	python-apt
pip install	python-chess
pip install	python-dateutil
pip install	python-louvain
pip install	python-rtmidi
pip install	python-slugify
pip install	python-utils
pip install	pytz
pip install	PyWavelets
pip install	PyYAML
pip install	pyzmq
pip install	qtconsole
pip install	requests
pip install	requests-oauthlib
pip install	resampy
pip install	retrying
pip install	rpy2
pip install	rsa
pip install	s3fs
pip install	s3transfer
pip install	scikit-image
pip install	scikit-learn
pip install	scipy
pip install	screen-resolution-extra
pip install	scs
pip install	seaborn
pip install	semantic-version
pip install	Send2Trash
pip install	setuptools
pip install	setuptools-git
pip install	Shapely
pip install	simplegeneric
pip install	six
pip install	sklearn
pip install	sklearn-pandas
pip install	smart-open
pip install	snowballstemmer
pip install	sortedcontainers
pip install	spacy
pip install	Sphinx
pip install	sphinxcontrib-websupport
pip install	SQLAlchemy
pip install	sqlparse
pip install	srsly
pip install	stable-baselines
pip install	statsmodels
pip install	sympy
pip install	tables
pip install	tabulate
pip install	tblib
pip install	tensor2tensor
pip install	tensorboard
pip install	tensorboardcolab
pip install	tensorflow
pip install	tensorflow-estimator
pip install	tensorflow-hub
pip install	tensorflow-metadata
pip install	tensorflow-probability
pip install	termcolor
pip install	terminado
pip install	testpath
pip install	text-unidecode
pip install	textblob
pip install	textgenrnn
pip install	tfds-nightly
pip install	tflearn
pip install	Theano
pip install	thinc
pip install	toolz
pip install	torch
pip install	torchsummary
pip install	torchtext
pip install	torchvision
pip install	tornado
pip install	tqdm
pip install	traitlets
pip install	tweepy
pip install	typing
pip install	tzlocal
pip install	umap-learn
pip install	uritemplate
pip install	urllib3
pip install	vega-datasets
pip install	wasabi
pip install	wcwidth
pip install	webencodings
pip install	Werkzeug
pip install	wheel
pip install	widgetsnbextension
pip install	wordcloud
pip install	wrapt
pip install	xarray
pip install	xgboost
pip install	xkit
pip install	xlrd
pip install	xlwt
pip install	yellowbrick
pip install	zict
pip install	zipp
pip install	zmq